# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OuRMEgKmso3x2r5EBU_nF-oGyofhHOxu
"""

month=int(input())
if month==1:
    print("January")
elif month==2:
    print("February")
elif month==3:
    print("March")
elif month==4:
    print("April")
elif month==5:
    print("May")
elif month==6:
    print("June")
elif month==7:
    print("July")
elif month==8:
    print("Agust")
elif month==9:
    print("September")
elif month==10:
    print("October")
elif month==11:
    print("November")
elif month==12:
    print("December")

number=int(input())
if number%2==0:
  print("чётное")
else: 
  print("нечётное")

N=int(input())
if N>40:
  print("stonks")
else: 
  print("not stonks")

year=int(input())
if year % 4 or (year %100 !=0 and year %400==0):
  print("високосный год")
else:
  print("не високосный год")

def is_prime(a):
  if a % 2 == 0:
    return a == 2
  d = 3
  while d * d <= a and a % d != 0:
    d += 2
  return d * d > a

print(is_prime(int(input("Enter a number: "))))

c = (-138/2)**1.3
a = int(input("Введите заначение первой переменной "))
b = int(input("Введите заначение второй переменной "))
if a / b == 3.6:
   a, b = b, a
elif b <= abs(c) and b >= (-69 / 28 ** 5.1)*4:
   a, b = b, a
print(a, b)

digits = []
for i  in range (5):
  print("Введите число № " , str(i + 1))
  x = int(input())
  digits.append(x)
DigitsArray = set(digits)
if len(DigitsArray) == len(digits):
  print("Все числа уникальны")
else: 
  print("В списке есть повторения")
even_numbers = 0
for i in range(len(digits)):
  if digits[i] % 2 == 0:
    even_numbers += 1
  else:
    pass
print("Всего четных чисел: ", str(even_numbers))    
NegativeNumbers = 0
for i in range(len(digits)):
  if digits[i] < 0:
    NegativeNumbers += 1
print("Всего отрцательных чисел: ", str(NegativeNumbers))
SpecifiedNumbers = 0
for i in range(len(digits)):
  if digits[i] >= -256 or digits[i] >= 1024:
    SpecifiedNumbers += 1
print("Всего чисел в  промежутке [-256 ; 1024]: ", str(SpecifiedNumbers));