# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QjIfFpfD2ziH0TvqNswXSZYbLEMpYUf1
"""

print("Hello World")

a=int(input())
b=int(input())
c=a+b
print(c)

a=int(input())
b=int(input())
c=int(input())
x=(a**2+b**2-c**3)/2
print(x)

a=int(input())
b=int(input())
c=(a+b)**2
print(c)

a=15
b=10
c=int(input())
d=(a+b)/c
print(c)

a=int(input())
b=int(input())
c=a**2+2*a*b+b**2
print(c)

a=int(input())
b=int(input())
c=a**2-((b/2)**2)
d=c**(1/2)
s=1/2*a*d
print(s)

a=int(input())
b=int(input())
c=((a**3+14)/5)*b
print(c)

a=int(input())
n=int(input())
x=a**2//n
print(x)

a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=(a/b)//(c/d)
f=a/c
x=a%c
print(e)
print(f)
print(x)

n=int(input())
d=n//86400
h=n//3600
m=n/60
print(d)
print(h)
print(m)

n=int(input())
x=n+n*11+n*111
print(x)